// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopHeader from "@/components/Top-Header";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Loading from "./loading";
import { Suspense } from 'react';
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}></body> 


export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className="min-h-screen flex flex-col">
        
        {/* Header at the top */}
        <header>
          <TopHeader />
          <Header />
        </header>

        {/* Main content that grows */}
        <main className="flex-1">
          <Suspense fallback={<Loading/>}>
            {children}
          </Suspense>
        </main>

        {/* Footer at the bottom */}
        <footer>
          <Footer />
        </footer>

      </body>
    </html>
  );
}
