// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopHeader from "@/components/Top-Header";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}></body> 


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className>
        <header>
          <TopHeader />
        </header>
        {children}
      </body>
    </html>
  );
}
